name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm exec tsc -p tsconfig.json --noEmit

      - name: Build
        env:
          NEXT_PUBLIC_SITE_URL: http://localhost:3000
          DATABASE_URL: postgresql://user:password@localhost:6543/dbname?pgbouncer=true&sslmode=require
          DIRECT_URL: postgresql://user:password@localhost:5432/dbname
        run: pnpm build

      - name: Lint (if present)
        run: pnpm --if-present lint